project:
  type: website

website:
  title: "Advent of Code 2022"
  navbar:
    title: false
    background: primary
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

      - section: Exercises
        contents:
        - href: exercises/day1.qmd
          text: Day 1
  page-footer:
    border: false
    background: light
    left: "Copyright 2022, Butch Landingin"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



