[project]
name = "butchland_aoc2022"
version = "0.0.1"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[tool.pyright]
reportShadowedImports = false

[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools >= 43.0.0',
]