# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "master",
        "doc_baseurl": "/butchland_aoc2022/",
        "doc_host": "https://butchland.github.io",
        "git_url": "https://github.com/butchland/butchland_aoc2022/tree/master/",
        "lib_path": "butchland_aoc2022",
    },
    "syms": {"butchland_aoc2022.day1": {}, "butchland_aoc2022.utils": {}},
}
